#!/usr/bin/env bash

function show_help() {
  name=$(basename ${0})
  cat <<EOF
${name} will retrieve a server's SSL certificate and
output the details via openssl to stdout.

Usage:
  ${name} FQDN
  ${name} -h | -?

Options:
  -h, -?  Show this help message
EOF
  exit 0
}

# Reset getopts for the shell
OPTIND=1

# Options parsing
while getopts "h?" opt; do
  case "${opt}" in
    h|\?)
      show_help
      exit 0
      ;;
  esac
done

command -v "openssl" >/dev/null 2>&1 || {
  echo >&2 "openssl is required to use this command!"
  exit 1
}

fqdn="${1}"
echo | openssl s_client -servername "${fqdn}" -connect "${fqdn}":443 2>/dev/null | openssl x509 -text

exit 0
