#!/usr/bin/env bash

#region helper functions
basename() {
  : "${1%/}"
  printf '%s\n' "${_##*/}"
}

show_help() {
  name=$(basename "${0}")
  cat <<EOF
${name} will knock on port 22 of the given host
and then SSH to the host once successful

Usage:
  ${name} HOST
  ${name} -h | --help | -?

Options:
  -h, --help, -?  Show this help message
EOF
  exit 0
}
#endregion helper functions

#region options parsing
# Options parsing
POSITIONAL=()
while [[ $# -gt 0 ]]; do
  case $1 in
    -\?|-h|--help)
      show_help
      ;;
    *)
      POSITIONAL+=("$1")
      shift
  esac
done
set -- "${POSITIONAL[@]}"

[[ $# -eq 0 ]] && show_help
#endregion options parsing

#regopm rrequirements
require() {
  name="${2:-${1}}"
  command -v "${1}" >/dev/null 2>&1 || {
    printf 'The %s tool is required to use this script!\n' "${name}" >&2
    [[ -z "${3}" ]] || printf '\tSee: %s\n' "${3}" >&2
    exit 1
  }
}

require 'nc'
require 'sleep'
require 'ssh'
#endregion requirements

#region requirements
# Stop macOS from taking over BASH_REMATCH
[[ ${OSTYPE} =~ ^darwin ]] && unset PROMPT_COMMAND

regex() {
  [[ $1 =~ $2 ]] && printf '%s\n' "${BASH_REMATCH[1]}"
}
#endregion requirements

#region main
if [[ $1 =~ @ ]]; then
  host=$(regex "${1}" "^.*@(.*)$")
else
  host="${1}"
fi

printf 'Knocking on %s...' "${host}"
until nc -vzw 2 "${host}" 22 2>/dev/null; do
  sleep 2
  printf '.'
done

printf ' \033[1;32mAnswered!\033[0;39m\n'
ssh "${1}"

exit 0
#endregion main
