#!/usr/bin/env bash

if [ "$(uname)" != "Darwin" ]; then
  echo "This toggle is only useful for macOS clients!"
  exit 1
fi

uuid="$(uuidgen | tr -d '-')"
tempFile="/tmp/${uuid}.img"

printf "Path to your bootable ISO? "
read sourceISO

if [ -e "${sourceISO}" ]; then
  printf "\n${sourceISO} exists!\n"

  printf "\nConverting ISO to IMG...\n"
  hdiutil convert -format UDRW -o "${tempFile}" "${sourceISO}"

  if [ -e "${tempFile}.dmg" ]; then
    printf "\nCorrecting automatic addition of .dmg to IMG filename...\n"
    mv "${tempFile}.dmg" "${tempFile}"
  fi

  OIFS="${IFS}"
  IFS=','
  devices=$(diskutil list | awk '/   0:/ { print $5" \t\t"$3" "$4" \t"$2"," }')
  printf "\nDEVICE \t\tSIZE\t\tVOLUME NAME\n"
  echo "${devices}"
  IFS="${OIFS}"

  printf "\nTarget device? "
  read target

  if [ `file /dev/${target} | awk '{print $2 }'` == "block" ]; then
    printf "\n/dev/${target} is valid!\n"
    echo -e "\033[1;31mANY DATA ON ${target} WILL BE OVERWRITTEN!\033[0;39m"
    read -p "Are you sure? " -n 1 -r
    echo

    if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
      printf "\nUnmounting ${target}...\n"
      diskutil unmountDisk "/dev/${target}"

      printf "\nWriting ${sourceISO} to ${target}... (may take a while)\n"
      sudo dd if="${tempFile}" of="/dev/r${target}" bs=1m

      printf "\nDone! Ejecting ${target} device!\n"
      diskutil eject "/dev/${target}"
    fi

    rm "${tempFile}"
  else
    echo >&2 "/dev/${target} does not appear to be a valid target!"
    rm "${tempFile}"
    exit 1
  fi
else
  echo >&2 "${sourceISO} does not exist!"
  exit 1
fi

exit 0
