#!/usr/bin/env bash

if [[ ! ${OSTYPE} =~ ^darwin ]]; then
  printf 'This toggle is only useful for macOS clients!\n' >&2
  exit 1
fi

require() {
  name="${2:-${1}}"
  command -v "${1}" >/dev/null 2>&1 || {
    printf 'The %s tool is required to use this script!\n' "${name}" >&2
    [[ -z "${3}" ]] || printf '\tSee: %s\n' "${3}" >&2
    exit 1
  }
}

require 'defaults'
require 'killall'

current=$(defaults read com.apple.finder AppleShowAllFiles)
if [ "${current}" == "YES" ]; then
  printf 'Hiding hidden files!\n'
  defaults write com.apple.finder AppleShowAllFiles NO;
else
  printf 'Showing hidden files!\n'
  defaults write com.apple.finder AppleShowAllFiles YES;
fi

killall Finder /System/Library/CoreServices/Finder.app

exit 0
