#!/usr/bin/env bash

show_help() {
  name=$(basename "${0}")
  cat <<EOF
${name} will retrieve a server's SSL certificate and
output the details via openssl to STDOUT.

Usage:
  ${name} FQDN
  ${name} -h | --help | -?

Options:
  -h, --help, -?  Show this help message
EOF
  exit 0
}

# Options parsing
POSITIONAL=()
while [[ $# -gt 0 ]]; do
  case $1 in
    -\?|-h|--help)
      show_help
      ;;
    *)
      POSITIONAL+=("$1")
      shift
  esac
done
set -- "${POSITIONAL[@]}"

[[ $# -eq 0 ]] && show_help

command -v openssl >/dev/null 2>&1 || {
  printf 'openssl is required to use this command!' >&2
  exit 1
}

echo | openssl s_client -servername "${1}" -connect "${1}":443 2>/dev/null | openssl x509 -text

exit 0
