#!/usr/bin/env bash

knife_config="${HOME}/.chef/knife.rb"

if [ ! -f "${knife_config}" ]; then
  echo "${knife_config} not found!"
  exit 1
fi

base_prefix="^[[:space:]]*"
disabled_prefix="${base_prefix}#[[:space:]]*"

edbs_enabled="${base_prefix}encrypted_data_bag_secret"
edbs_disabled="${disabled_prefix}encrypted_data_bag_secret"
ksf_enabled="${base_prefix}knife\[:secret_file]"
ksf_disabled="${disabled_prefix}knife\[:secret_file]"

if grep -q "${edbs_disabled}" "${knife_config}"; then
  echo "Enabling ecrypted data bag secret!"
  sed -i '' "s/${edbs_disabled}/encrypted_data_bag_secret/" "${knife_config}"
elif grep -q "${edbs_enabled}" "${knife_config}"; then
  echo "Disabling encrypted data bag secret!"
  sed -i '' "s/${edbs_enabled}/# encrypted_data_bag_secret/" "${knife_config}"
else
  echo "No encrypted data bag secret field found in ${knife_config}!"
fi

if grep -q "${ksf_disabled}" "${knife_config}"; then
  echo "Enabling knife[:secret_file]!"
  sed -i '' "s/${ksf_disabled}/knife\[:secret_file]/" "${knife_config}"
elif grep -q "${ksf_enabled}" "${knife_config}"; then
  echo "Disabling knife[:secret_file]!"
  sed -i '' "s/${ksf_enabled}/# knife\[:secret_file]/" "${knife_config}"
else
  echo "No knife[:secret_file] field found in ${knife_config}!"
fi

exit 0
